"""empty message

Revision ID: 2373afa3563a
Revises: 219537c612fa
Create Date: 2023-02-26 18:59:08.544503

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2373afa3563a'
down_revision = '219537c612fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shows', schema=None) as batch_op:
        batch_op.add_column(sa.Column('start_time', sa.DateTime(), nullable=True))
    op.execute('UPDATE shows SET start_time = timestamp')
    op.alter_column('shows', 'start_time', nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shows', schema=None) as batch_op:
        batch_op.drop_column('start_time')

    # ### end Alembic commands ###
